# Generated by Django 5.1.1 on 2025-02-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
