# Generated by Django 5.1.1 on 2025-02-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0007_alter_customuser_telephone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headmaster',
        ),
        migrations.DeleteModel(
            name='studentLogin',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='term',
            new_name='Semester',
        ),
        migrations.RenameField(
            model_name='uploadresult',
            old_name='subject_name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='uploadresult',
            old_name='teacher_name',
            new_name='lecture_name',
        ),
        migrations.RemoveField(
            model_name='result',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='result',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='result',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='result',
            name='year',
        ),
        migrations.AddField(
            model_name='result',
            name='Assignments',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='Level',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='Quizzes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadresult',
            name='subject_file',
            field=models.FileField(upload_to='ResultFiles'),
        ),
    ]
