# Generated by Django 5.1.1 on 2025-03-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0008_delete_headmaster_delete_studentlogin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmaster',
            name='ClassHanlder',
        ),
    ]
