# Generated by Django 5.1.1 on 2025-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0009_remove_formmaster_classhanlder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Class',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
