# Generated by Django 5.1.1 on 2025-03-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0010_customuser_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencereport',
            name='Class',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absencereport',
            name='reason',
            field=models.TextField(max_length=100),
        ),
    ]
