# Generated by Django 5.1.1 on 2025-03-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0011_absencereport_class_alter_absencereport_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Class',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
