# Generated by Django 5.1.1 on 2025-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0012_alter_customuser_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Class',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
