# Generated by Django 5.1.1 on 2025-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0013_alter_customuser_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencereport',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
