# Generated by Django 5.1.1 on 2025-03-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0015_alter_customuser_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Message', models.TextField()),
                ('readmore', models.CharField(max_length=100)),
            ],
        ),
    ]
