# Generated by Django 5.1.1 on 2025-03-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0017_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='publication_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
