# Generated by Django 5.1.1 on 2025-03-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0018_publications_publication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='publication_number',
            field=models.IntegerField(),
        ),
    ]
