# Generated by Django 5.1.1 on 2025-03-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0019_alter_publications_publication_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='publication_link',
            field=models.CharField(max_length=100),
        ),
    ]
