# Generated by Django 5.1.1 on 2025-03-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0020_alter_publications_publication_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staticIndexNumbers',
            new_name='ValidIndexNumbers',
        ),
        migrations.RenameField(
            model_name='validindexnumbers',
            old_name='Student_IndexNumber',
            new_name='IndexNumbers',
        ),
    ]
