# Generated by Django 5.1.1 on 2025-03-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0021_rename_staticindexnumbers_validindexnumbers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidIndexNumbers',
            new_name='IndexNumbers',
        ),
    ]
