# Generated by Django 5.1.1 on 2025-05-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0023_chatbot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='user',
            new_name='user_id',
        ),
    ]
