# Generated by Django 5.1.1 on 2025-05-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0024_rename_user_chatbot_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='user_id',
            new_name='user',
        ),
    ]
