# Generated by Django 5.2.3 on 2025-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0026_uploadindexnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formmaster',
            options={'verbose_name': 'Teaching Assistance'},
        ),
        migrations.AlterModelOptions(
            name='indexnumbers',
            options={'verbose_name': 'Index Number'},
        ),
        migrations.AddField(
            model_name='about',
            name='myimage',
            field=models.ImageField(default=1, upload_to='myimage'),
            preserve_default=False,
        ),
    ]
