# Generated by Django 5.2.3 on 2025-06-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0027_alter_formmaster_options_alter_indexnumbers_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadIndexNumber',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Info'},
        ),
    ]
